import zod from 'zod';
import type { ProjectType } from '#types';

const DATA = (<Omit<ProjectType, 'id'>[]>[
  {
    title: 'VK — инфраструктура vk.com',
    description:
      'Внутренние стандарты и инструменты для разработки vk.com с упором на производительность и качество кода.',
    roles: [Role.FRONTEND, Role.ARCHITECT],
    categories: [Category.FRONTEND, Category.DEVOPS],
    stack: [
      Technology.REACT,
      Technology.TYPE_SCRIPT,
      Technology.ESLINT,
      Technology.OXC,
      Technology.EFFECTOR,
      Technology.PHP,
    ],
    tasks: [
      'Проектирование и развитие внутренних инструментов фронтенд-инфраструктуры для vk.com',
      'Оптимизация линтеров, сборки и проверки качества кода для большого монорепозитория',
      'Исследование и внедрение новых инструментов и практик разработки',
      'Разработка внутренних CLI, плагинов и конфигов, которые используют другие команды',
      'Оптимизация производительности и стабильности фронтенд-проекта на уровне платформы',
    ],
    period: {
      from: ['2024', '05'],
      to: [],
    },
  },
  {
    title: 'Яндекс Учебник / Yandex Education',
    description: 'Обновлённая версия Яндекс Учебника с упором на предмет «Программирование» и современный стек.',
    roles: [Role.FRONTEND],
    categories: [Category.FRONTEND],
    stack: [Technology.REACT, Technology.TYPE_SCRIPT],
    tasks: [
      'Перенос легаси-функционала Учебника на современный стек React + TypeScript',
      'Отказ от lodash и переписывание утилит и бизнес-логики на собственные решения',
      'Рефакторинг старых модулей и типизация критичных участков кода',
      'Обновление зависимостей и выравнивание версий библиотек в большом проекте',
      'Улучшение UX и интерфейса раздела по программированию с учётом методики обучения',
    ],
    period: {
      from: ['2025', '05'],
      to: ['2025', '11'],
    },
  },
  {
    title: 'Альфа-Банк — маршруты подписания документов',
    description: 'Модуль настройки маршрутов подписания документов для юридических лиц и ИП.',
    roles: [Role.FRONTEND],
    categories: [Category.FRONTEND],
    stack: [
      Technology.REACT,
      Technology.REDUX_SAGA,
      Technology.STYLE_MODULES,
      Technology.TYPE_SCRIPT,
      Technology.KUBERNETES,
    ],
    tasks: [
      'Разработка интерфейса конструктора маршрутов подписания с большим количеством правил и условий',
      'Проработка сложной бизнес-логики согласований и статусов документов',
      'Добавление и поддержка автотестов для ключевых пользовательских сценариев',
      'Техдолг: обновление проекта, зависимостей и устранение уязвимостей',
      'Подготовка фронтенд-сервиса к работе в Kubernetes-инфраструктуре банка',
    ],
    period: {
      from: ['2023', '08'],
      to: ['2024', '05'],
    },
  },
  {
    title: 'Альфа-Банк — модуль конвертации валют',
    description: 'Модуль мониторинга и управления конвертациями валют с отображением прогресса операций.',
    roles: [Role.FRONTEND],
    categories: [Category.FRONTEND],
    stack: [
      Technology.REACT,
      Technology.REDUX_TOOLKIT,
      Technology.STYLE_MODULES,
      Technology.TYPE_SCRIPT,
      Technology.KUBERNETES,
    ],
    tasks: [
      'Разработка интерфейсов для мониторинга и детализации конвертаций валют в режиме близком к реальному времени',
      'Реализация бизнес-логики статусов, прогресса и истории операций',
      'Написание автотестов для критичных сценариев работы пользователей',
      'Подготовка и адаптация фронтенда для работы в Kubernetes-окружении',
    ],
    period: {
      from: ['2024', '02'],
      to: ['2024', '04'],
    },
  },
  {
    title: 'RedCat — CRM для агентств недвижимости',
    description: 'CRM-система для управления агентством недвижимости, сотрудниками и правами доступа.',
    roles: [Role.FRONTEND],
    categories: [Category.FRONTEND],
    stack: [Technology.REACT, Technology.NEXT, Technology.PROP_TYPES],
    tasks: [
      'Разработка интерфейсов профиля агента и агентства',
      'Реализация редактирования данных сотрудников и управления их ролями и правами',
      'Оптимизация UX для ежедневной работы риелторов и руководителей',
      'Улучшение производительности и отзывчивости интерфейса',
    ],
    period: {
      from: ['2024', '01'],
      to: ['2024', '03'],
    },
  },
  {
    title: 'MindLoom — психологическая образовательная платформа',
    description: 'Платформа по психологическому саморазвитию с чатами между экспертом и студентом.',
    roles: [Role.FRONTEND, Role.DESIGN, Role.SECURITY],
    categories: [Category.FRONTEND],
    stack: [Technology.REACT, Technology.TYPE_SCRIPT, Technology.FRAMER_MOTION, Technology.SCSS],
    tasks: [
      'Разработка интерфейса чата для экспертов и студентов с акцентом на плавные анимации',
      'Проработка адаптивного интерфейса: разные layout’ы для десктопа и мобильных при общей кодовой базе',
      'Создание сложной CSS-архитектуры без дублирования, с визуально различными слоями для разных устройств',
      'Тотальная анимация всех переходов и состояний (сообщения, статусы, списки, обновления текста)',
      'Проведение аудита безопасности: анализ CSP, работы с токенами и ключами, хранения секретов',
      'Исправление проблем безопасности: CSRF, лишние данные в API, dangerouslySetInnerHTML, утечки e-mail и телефонов',
    ],
    period: {
      from: [''],
      to: [''],
    },
  },
  {
    title: 'Don’t Touch My Skin — сайт бренда косметики',
    description: 'Мультиязычный промо-сайт бренда ухода за кожей с упором на скорость и безопасность.',
    roles: [Role.FRONTEND],
    categories: [Category.FRONTEND],
    stack: [Technology.NUXT, Technology.TYPE_SCRIPT, Technology.SCSS, Technology.NUXT_STRICT_FETCH, Technology.NGINX],
    tasks: [
      'Разработка сайта на Nuxt с упором на высокие показатели Lighthouse (performance, accessibility, SEO)',
      'Реализация мультиязычности и структурированных данных для SEO',
      'Внедрение собственной библиотеки nuxt-strict-fetch для безопасной и контролируемой работы с API',
      'Проработка кэширования и настройки заголовков на уровне сервера и клиента',
      'Добавление анимаций и микровзаимодействий без ущерба для скорости загрузки',
    ],
    period: {
      from: [''],
      to: [''],
    },
  },
  {
    title: 'Digirate — платформа статей и экспертизы',
    description: 'Платформа публикаций и экспертных разборов с кастомной архитектурой фронта и бэка.',
    roles: [Role.FRONTEND, Role.BACKEND, Role.DEVOPS, Role.DESIGN, Role.ARCHITECT],
    categories: [Category.FRONTEND, Category.BACKEND, Category.DEVOPS],
    stack: [
      Technology.NUXT,
      Technology.NEST,
      Technology.NUXT_STRICT_FETCH,
      Technology.TYPE_SCRIPT,
      Technology.POSTGRE_SQL,
      Technology.DOCKER,
      Technology.NGINX,
    ],
    tasks: [
      'Проектирование архитектуры платформы: фронтенд, backend и модель домена с нуля',
      'Реализация фронтенда на Nuxt с использованием Nuxt Layers и модульной структуры',
      'Разработка backend на NestJS с авторизацией, ролями и продуманными API',
      'Интеграция с Asmy для деплоя и управления инфраструктурой',
      'Настройка Docker-окружения и CI/CD для проекта (локально и на сервере)',
    ],
    period: {
      from: [''],
      to: [''],
    },
  },
  {
    title: 'Splav — сайт музыкального проекта',
    description: 'Арт-сайт музыкальной группы с полностью резиновой версткой и контентом на Markdown.',
    roles: [Role.FRONTEND, Role.DESIGN],
    categories: [Category.FRONTEND],
    stack: [Technology.NUXT, Technology.TYPE_SCRIPT, Technology.MARKDOWN, Technology.SCSS],
    tasks: [
      'Разработка резиновой верстки, которая корректно тянется на любых разрешениях',
      'Интеграция markdown-контента и настройка удобной редакторской модели',
      'Создание визуально цельного арт-стиля и анимаций под музыкальный проект',
      'Оптимизация загрузки медиа и плавности скролла',
    ],
    period: {
      from: [''],
      to: [''],
    },
  },
  {
    title: 'Журнал «Графин» — экономический онлайн-журнал',
    description: 'Онлайн-журнал о финансах и экономике с длинными материалами и удобной лентой чтения.',
    roles: [Role.FRONTEND],
    categories: [Category.FRONTEND],
    stack: [Technology.NEXT, Technology.REACT, Technology.TYPE_SCRIPT, Technology.SCSS],
    tasks: [
      'Разработка интерфейсов ленты статей и страниц материалов',
      'Реализация системы тегов, фильтрации и бесконечной прокрутки',
      'Оптимизация читаемости материалов: типографика, сетка, работа с длинными текстами',
      'Участие в доработке дизайна и UX под редакторскую команду',
    ],
    period: {
      from: [''],
      to: [''],
    },
  },
  {
    title: 'Журнал «Графин» — чат технической поддержки',
    description: 'Встраиваемый чат техподдержки для журнала с административной панелью операторов.',
    roles: [Role.FRONTEND, Role.BACKEND, Role.DEVOPS, Role.DESIGN],
    categories: [Category.FRONTEND, Category.BACKEND, Category.DEVOPS],
    stack: [
      Technology.NEXT,
      Technology.REACT,
      Technology.PRIME_REACT,
      Technology.NEST,
      Technology.SOCKET_IO,
      Technology.POSTGRE_SQL,
      Technology.DOCKER,
    ],
    tasks: [
      'Полная разработка виджета чата и административной части с нуля',
      'Проектирование протокола общения по WebSocket и статусов диалогов',
      'Создание адаптивного интерфейса с удобной работой и на десктопе, и на мобильных',
      'Проработка дизайна виджета в стилистике журнала и мягких анимаций',
      'Настройка Docker-окружения и деплоя сервиса',
    ],
    period: {
      from: ['2022', '02'],
      to: ['2022', '02'],
    },
  },
  {
    title: 'nuxt-strict-fetch (open source)',
    description: 'Библиотека для строгого и безопасного управления HTTP-запросами в Nuxt-проектах.',
    roles: [Role.FRONTEND, Role.ARCHITECT],
    categories: [Category.FRONTEND],
    stack: [Technology.TYPE_SCRIPT, Technology.NUXT, Technology.OFETCH],
    tasks: [
      'Проектирование API библиотеки для контроля запросов, ошибок и состояний загрузки',
      'Реализация строгой типизации и единообразной обработки ошибок',
      'Оптимизация DX: простые хелперы, читаемые сигнатуры и предсказуемое поведение',
      'Поддержка библиотеки и внедрение в реальные коммерческие проекты',
    ],
    period: {
      from: [''],
      to: [''],
    },
  },
  {
    title: 'Альфа-Банк — административная панель сотрудников',
    description: 'Панель для работы сотрудников банка с клиентами и машиночитаемыми доверенностями.',
    roles: [Role.FRONTEND],
    categories: [Category.FRONTEND],
    stack: [
      Technology.REACT,
      Technology.REDUX,
      Technology.STYLE_MODULES,
      Technology.TYPE_SCRIPT,
      Technology.KUBERNETES,
    ],
    tasks: [
      'Разработка новых административных интерфейсов и сценариев работы сотрудников',
      'Внедрение новых возможностей в существующий продукт с учётом банковских ограничений',
      'Доработка и поддержка автотестов',
      'Обновление стека и подготовка сервиса к работе в Kubernetes',
    ],
    period: {
      from: ['2023', '01'],
      to: [],
    },
  },
  {
    title: 'Альфа-Банк — профиль юридического лица',
    description: 'Интерфейсы для работы с данными организаций, доступами и электронными подписями.',
    roles: [Role.FRONTEND],
    categories: [Category.FRONTEND],
    stack: [Technology.REACT, Technology.REDUX, Technology.STYLE_MODULES, Technology.TYPE_SCRIPT],
    tasks: [
      'Разработка и развитие интерфейсов профиля юридического лица',
      'Реализация функционала управления доступами и подписями',
      'Доработка автотестов и исправление сложных UI-багов',
    ],
    period: {
      from: ['2022', '05'],
      to: ['2022', '12'],
    },
  },
  {
    title: 'Asmy — панель управления сервером и Docker-инфраструктурой',
    description: 'Мощная веб-панель для управления Docker-контейнерами, сетями, хранилищами и веб-сервером.',
    roles: [Role.FRONTEND, Role.BACKEND, Role.DEVOPS, Role.DESIGN, Role.ARCHITECT],
    categories: [Category.FRONTEND, Category.BACKEND, Category.DEVOPS],
    stack: [
      Technology.DOCKER,
      Technology.GO,
      Technology.GIN,
      Technology.GORM,
      Technology.POSTGRE_SQL,
      Technology.REDIS,
      Technology.CADDY,
      Technology.VUE,
      Technology.NAIVE_UI,
      Technology.TYPE_SCRIPT,
    ],
    tasks: [
      'Проектирование архитектуры сервиса управления сервером и контейнерами',
      'Реализация backend на Go с использованием Docker API, управлением TLS и доменами',
      'Создание фронтенда с удобной панелью, ролями и доступами, возможностью работы с мобильных',
      'Интеграция веб-терминала и файлового менеджера в интерфейс',
      'Полный дизайн интерфейса с нуля и продумывание UX для админов и DevOps-инженеров',
    ],
    period: {
      from: ['2021'],
      to: ['2022'],
    },
  },
  {
    title: 'Gazprom — инструмент для Data Science pipelines',
    description: 'Веб-интерфейс контроля и мониторинга Data Science-пайплайнов.',
    roles: [Role.FRONTEND],
    categories: [Category.FRONTEND],
    stack: [Technology.REACT, Technology.REDUX, Technology.TYPE_SCRIPT],
    tasks: [
      'Разработка всех пользовательских интерфейсов для контроля пайплайнов',
      'Реализация функционала мониторинга статусов, истории и ошибок',
      'Интеграция с бэкендом и адаптация под инфраструктуру заказчика',
    ],
    period: {
      from: ['2020'],
      to: ['2021'],
    },
  },
  {
    title: 'Gazprom — система «Интеллектуальная собственность»',
    description: 'Система управления объектами интеллектуальной собственности компании.',
    roles: [Role.FRONTEND],
    categories: [Category.FRONTEND],
    stack: [Technology.VUE, Technology.NUXT, Technology.PUG, Technology.SCSS, Technology.VUEX, Technology.AXIOS],
    tasks: [
      'Единоличная разработка фронтенда системы на основе Nuxt',
      'Реализация множества сложных форм с несколькими этапами согласования',
      'Проработка UX для юристов и сотрудников, работающих с объектами ИС',
      'Оптимизация работы с формами и валидацией на большом количестве полей',
    ],
    period: {
      from: ['2019'],
      to: ['2020'],
    },
  },
  {
    title: 'Gazprom — управление производственной мощностью',
    description: 'Инструмент поддержки решений по эффективности реализации проектов.',
    roles: [Role.FRONTEND],
    categories: [Category.FRONTEND],
    stack: [Technology.TYPE_SCRIPT, Technology.REACT, Technology.MOBX, Technology.EMOTION, Technology.D3],
    tasks: [
      'Разработка интерфейсов для работы с графиками, диаграммами и документами',
      'Реализация бизнес-логики расчётов и отображения ключевых показателей',
      'Создание панели администрирования и вспомогательных экранов',
    ],
    period: {
      from: ['2019'],
      to: ['2021'],
    },
  },
  {
    title: 'Gazprom — мониторинг экономической эффективности портфелей',
    description: 'Аналитическая система для оценки экономической эффективности портфелей проектов.',
    roles: [Role.FRONTEND, Role.TEAM_LEAD],
    categories: [Category.FRONTEND],
    stack: [Technology.REACT, Technology.REDUX, Technology.D3, Technology.TYPE_SCRIPT],
    tasks: [
      'Разработка новых интерфейсов для аналитики и визуализации данных',
      'Работа с графиками, диаграммами и вложенными документами',
      'Оптимизация проекта и подготовка к развёртыванию у заказчика',
      'Координация задач на фронтенде и контроль качества реализации',
    ],
    period: {
      from: ['2020'],
      to: [],
    },
  },
  {
    title: 'Panasonic — промо-сайты Lumix и Experience Fresh',
    description: 'Промо-сайты для продвижения продуктов Panasonic.',
    roles: [Role.FRONTEND, Role.DEVOPS],
    categories: [Category.FRONTEND, Category.DEVOPS],
    stack: [
      Technology.VUE,
      Technology.NUXT,
      Technology.VUEX,
      Technology.PUG,
      Technology.SCSS,
      Technology.GRAPH_QL,
      Technology.DOCKER,
      Technology.GITLAB_CI,
    ],
    tasks: [
      'Разработка промо-страниц и интерактивных блоков',
      'Интеграция с backend через GraphQL',
      'Настройка генерации тестовых стендов через CI/CD',
    ],
    period: {
      from: ['2020'],
      to: ['2020'],
    },
  },
  {
    title: 'Panasonic — интернет-магазин Eplaza',
    description: 'Официальный интернет-магазин техники Panasonic.',
    roles: [Role.FRONTEND, Role.DEVOPS],
    categories: [Category.FRONTEND, Category.DEVOPS],
    stack: [
      Technology.VUE,
      Technology.NUXT,
      Technology.VUEX,
      Technology.PUG,
      Technology.SCSS,
      Technology.DOCKER,
      Technology.GITLAB_CI,
      Technology.NGINX,
    ],
    tasks: [
      'Разработка новых интерфейсов и бизнес-функционала магазина',
      'Настройка системы генерации тестовых стендов через CI/CD',
      'Усиление безопасности проекта и корректная работа под нагрузкой',
    ],
    period: {
      from: ['2020'],
      to: ['2020'],
    },
  },
  {
    title: 'Grow Heads — образовательная платформа',
    description: 'Платформа по обучению современным IT-профессиям.',
    roles: [Role.FRONTEND, Role.DEVOPS, Role.TEAM_LEAD, Role.ARCHITECT],
    categories: [Category.FRONTEND, Category.DEVOPS],
    stack: [
      Technology.REACT,
      Technology.MOBX,
      Technology.STYLE_MODULES,
      Technology.DOCKER,
      Technology.GO,
      Technology.GITLAB_CI,
      Technology.POSTGRE_SQL,
    ],
    tasks: [
      'Принятие архитектурных решений на фронтенде',
      'Координация работы команды и ревью кода',
      'Настройка генерации тестовых стендов и CI/CD',
      'Повышение безопасности и устойчивости проекта',
    ],
    period: {
      from: ['2020', '10'],
      to: ['2022', '05'],
    },
  },
  {
    title: 'Приложение онлайн-кинотеатра для Smart TV',
    description: 'Приложение онлайн-кинотеатра для Tizen OS и WebOS.',
    roles: [Role.FRONTEND],
    categories: [Category.FRONTEND],
    stack: [Technology.JAVA_SCRIPT, Technology.WEBPACK, Technology.TIZEN_FRAMEWORK, Technology.WEBOS_FRAMEWORK],
    tasks: [
      'Разработка интерфейса и логики приложения для Smart TV',
      'Адаптация UI под особенности пульта и навигации по ТВ',
    ],
    period: {
      from: ['2020', '08'],
      to: ['2020', '08'],
    },
  },
  {
    title: 'Mail.ru — сайт премии и библиотеки AI-кейсов',
    description: 'Сайт премии и библиотеки кейсов по использованию искусственного интеллекта.',
    roles: [Role.FRONTEND, Role.DEVOPS],
    categories: [Category.FRONTEND, Category.DEVOPS],
    stack: [Technology.VUE, Technology.NUXT, Technology.VUEX, Technology.PUG, Technology.SCSS, Technology.GSAP],
    tasks: [
      'Разработка проекта и сложной анимации на GSAP',
      'Добавление новых функций и интерактивных блоков',
      'Оптимизация производительности и поддержка старых браузеров',
    ],
    period: {
      from: ['2020', '09'],
      to: ['2021', '03'],
    },
  },
  {
    title: 'Сервис работы с IoT в автомобилях',
    description: 'Сервис мониторинга состояния автомобиля по датчикам и управления сервисными услугами.',
    roles: [Role.FRONTEND, Role.BACKEND],
    categories: [Category.FRONTEND, Category.BACKEND],
    stack: [Technology.ANGULAR, Technology.LARAVEL, Technology.POSTGRE_SQL],
    tasks: [
      'Разработка интерфейсов для работы с данными датчиков и автомобилями',
      'Создание API для мобильного приложения',
      'Интерфейсы для управления IoT-устройствами и сервисными действиями',
    ],
    period: {
      from: ['2017'],
      to: ['2019', '03'],
    },
  },
  {
    title: 'Vitamina — интернет-магазин полезных продуктов',
    description: 'Магазин полезных продуктов и добавок на легаси-стеке Laravel + AngularJS.',
    roles: [Role.FRONTEND, Role.BACKEND],
    categories: [Category.FRONTEND, Category.BACKEND],
    stack: [Technology.LARAVEL, Technology.ANGULAR_JS, Technology.MY_SQL],
    tasks: [
      'Погружение в чужой легаси-код без авторов проекта',
      'Поддержка и развитие функционала магазина на связке Laravel + AngularJS',
      'Поиск и исправление скрытых багов и нестабильных мест',
      'Точечные улучшения производительности и UX без полного переписывания',
    ],
    period: {
      from: [''],
      to: [''],
    },
  },
  {
    title: 'Доклад на конференции «Стачка» (Frontend)',
    description: 'Доклад о практической оптимизации скорости загрузки сайтов.',
    roles: [Role.SPEAKER],
    categories: [Category.FRONTEND],
    stack: [],
    tasks: [
      'Разбор подходов к оптимизации изображений и работе оптимизаторов',
      'Рассмотрение кэширования на разных уровнях (браузер, CDN, сервер)',
      'Обсуждение оптимизации рендеринга, доставки HTTP-сообщений и API',
    ],
    period: {
      from: ['2023', '09'],
      to: ['2023', '09'],
    },
  },
]).map<ProjectType>(({ period, ...item }, index) => ({ ...item, id: index + 1 }));

export default defineEventHandler(async (event) => {
  const { category } = await getValidatedQuery(event, zod.object({ category: zod.enum(Category) }).parse);

  return DATA.filter((item) => item.categories.includes(category));
});
