export const CATEGORY_MAP: Record<Category, string> = {
  [Category.FRONTEND]: 'Frontend',
  [Category.BACKEND]: 'Backend',
  [Category.DEVOPS]: 'DevOps',
};

export const ROLE_MAP: Record<Role, string> = {
  [Role.FRONTEND]: 'Frontend разработчик',
  [Role.BACKEND]: 'Backend разработчик',
  [Role.DEVOPS]: 'DevOps инженер',
  [Role.DESIGN]: 'Дизайнер',
  [Role.TEAM_LEAD]: 'Team-Leader',
  [Role.ARCHITECT]: 'Архитектор',
  [Role.SPEAKER]: 'Спикер',
  [Role.SECURITY]: 'Специалист по Безопасности',
};

export const TECHNOLOGY_MAP: Record<Technology, string> = {
  [Technology.ANGULAR]: 'Angular',
  [Technology.ANGULAR_JS]: 'AngularJS',
  [Technology.AXIOS]: 'Axios',
  [Technology.CADDY]: 'Caddy',
  [Technology.D3]: 'D3.js',
  [Technology.DOCKER]: 'Docker',
  [Technology.ESLINT]: 'ESLint',
  [Technology.EFFECTOR]: 'Effector',
  [Technology.EMOTION]: 'Emotion',
  [Technology.FRAMER_MOTION]: 'Framer Motion',
  [Technology.GSAP]: 'GSAP',
  [Technology.GIN]: 'Gin',
  [Technology.GITLAB_CI]: 'GitLab CI',
  [Technology.GO]: 'Go',
  [Technology.GORM]: 'Gorm',
  [Technology.GRAPH_QL]: 'GraphQL',
  [Technology.JAVA_SCRIPT]: 'JavaScript',
  [Technology.KUBERNETES]: 'Kubernetes',
  [Technology.LARAVEL]: 'Laravel',
  [Technology.MARKDOWN]: 'Markdown',
  [Technology.MOBX]: 'MobX',
  [Technology.MY_SQL]: 'MySQL',
  [Technology.NAIVE_UI]: 'Naive UI',
  [Technology.NEST]: 'NestJS',
  [Technology.NEXT]: 'Next.js',
  [Technology.NGINX]: 'Nginx',
  [Technology.NUXT]: 'Nuxt.js',
  [Technology.OXC]: 'Oxc',
  [Technology.PHP]: 'PHP',
  [Technology.POSTGRE_SQL]: 'PostgreSQL',
  [Technology.PRIME_REACT]: 'PrimeReact',
  [Technology.PROP_TYPES]: 'PropTypes',
  [Technology.PUG]: 'Pug',
  [Technology.REACT]: 'React',
  [Technology.REDIS]: 'Redis',
  [Technology.REDUX]: 'Redux',
  [Technology.REDUX_TOOLKIT]: 'Redux Toolkit',
  [Technology.REDUX_SAGA]: 'Redux-Saga',
  [Technology.SCSS]: 'SCSS',
  [Technology.STYLE_MODULES]: 'Style Modules',
  [Technology.SOCKET_IO]: 'Socket.IO',
  [Technology.TIZEN_FRAMEWORK]: 'Tizen Framework',
  [Technology.TYPE_SCRIPT]: 'TypeScript',
  [Technology.VUE]: 'Vue.js',
  [Technology.VUEX]: 'Vuex',
  [Technology.WEBOS_FRAMEWORK]: 'WebOS Framework',
  [Technology.WEBPACK]: 'Webpack',
  [Technology.NUXT_STRICT_FETCH]: 'nuxt-strict-fetch',
  [Technology.OFETCH]: 'ofetch',
};
