export const CATEGORY_MAP: Record<Category, string> = {
  [Category.FRONTEND]: 'Frontend',
  [Category.BACKEND]: 'Backend',
  [Category.DEVOPS]: 'DevOps',
};

export const ROLE_MAP: Record<Role, string> = {
  [Role.FRONTEND]: 'Frontend разработчик',
  [Role.BACKEND]: 'Backend разработчик',
  [Role.DEVOPS]: 'DevOps инженер',
  [Role.DESIGN]: 'Дизайнер',
  [Role.TEAM_LEAD]: 'Team-Leader',
  [Role.ARCHITECT]: 'Архитектор',
  [Role.SPEAKER]: 'Спикер',
  [Role.SECURITY]: 'Специалист по Безопасности',
};

export const TECHNOLOGY_MAP: Record<Technology, string> = {
  [Technology.ANGULAR]: 'Angular',
  [Technology.ANGULAR_JS]: 'AngularJS',
  [Technology.AXIOS]: 'Axios',
  [Technology.CADDY]: 'Caddy',
  [Technology.D3]: 'D3.js',
  [Technology.DOCKER]: 'Docker',
  [Technology.ESLINT]: 'ESLint',
  [Technology.EFFECTOR]: 'Effector',
  [Technology.EMOTION]: 'Emotion',
  [Technology.FRAMER_MOTION]: 'Framer Motion',
  [Technology.GSAP]: 'GSAP',
  [Technology.GIN]: 'Gin',
  [Technology.GITLAB_CI]: 'GitLab CI',
  [Technology.GITHUB_ACTIONS]: 'GitHub Actions',
  [Technology.GO]: 'Go',
  [Technology.GORM]: 'Gorm',
  [Technology.GRAPH_QL]: 'GraphQL',
  [Technology.JAVA_SCRIPT]: 'JavaScript',
  [Technology.KUBERNETES]: 'Kubernetes',
  [Technology.LARAVEL]: 'Laravel',
  [Technology.MARKDOWN]: 'Markdown',
  [Technology.MOBX]: 'MobX',
  [Technology.MY_SQL]: 'MySQL',
  [Technology.NAIVE_UI]: 'Naive UI',
  [Technology.NEST]: 'NestJS',
  [Technology.NEXT]: 'Next.js',
  [Technology.NGINX]: 'Nginx',
  [Technology.NUXT]: 'Nuxt.js',
  [Technology.OXC]: 'Oxc',
  [Technology.PHP]: 'PHP',
  [Technology.POSTGRE_SQL]: 'PostgreSQL',
  [Technology.PRIME_REACT]: 'PrimeReact',
  [Technology.PROP_TYPES]: 'PropTypes',
  [Technology.PUG]: 'Pug',
  [Technology.REACT]: 'React',
  [Technology.REDIS]: 'Redis',
  [Technology.REDUX]: 'Redux',
  [Technology.REDUX_TOOLKIT]: 'Redux Toolkit',
  [Technology.REDUX_SAGA]: 'Redux-Saga',
  [Technology.SCSS]: 'SCSS',
  [Technology.STYLE_MODULES]: 'Style Modules',
  [Technology.SOCKET_IO]: 'Socket.IO',
  [Technology.TIZEN_FRAMEWORK]: 'Tizen Framework',
  [Technology.TYPE_SCRIPT]: 'TypeScript',
  [Technology.VUE]: 'Vue.js',
  [Technology.VUEX]: 'Vuex',
  [Technology.WEBOS_FRAMEWORK]: 'WebOS Framework',
  [Technology.WEBPACK]: 'Webpack',
  [Technology.NUXT_STRICT_FETCH]: 'nuxt-strict-fetch',
  [Technology.OFETCH]: 'ofetch',
};

export const TECHNOLOGY_GROUP = {
  [Category.FRONTEND]: [
    Technology.NUXT,
    Technology.VUE,
    Technology.NEXT,
    Technology.REACT,
    Technology.ANGULAR,
    Technology.ANGULAR_JS,
    Technology.AXIOS,
    Technology.D3,
    Technology.ESLINT,
    Technology.EFFECTOR,
    Technology.EMOTION,
    Technology.FRAMER_MOTION,
    Technology.GSAP,
    Technology.GRAPH_QL,
    Technology.JAVA_SCRIPT,
    Technology.MARKDOWN,
    Technology.MOBX,
    Technology.NAIVE_UI,
    Technology.OXC,
    Technology.PRIME_REACT,
    Technology.PROP_TYPES,
    Technology.PUG,
    Technology.REDUX,
    Technology.REDUX_TOOLKIT,
    Technology.REDUX_SAGA,
    Technology.SCSS,
    Technology.STYLE_MODULES,
    Technology.SOCKET_IO,
    Technology.TIZEN_FRAMEWORK,
    Technology.TYPE_SCRIPT,
    Technology.VUEX,
    Technology.WEBOS_FRAMEWORK,
    Technology.WEBPACK,
    Technology.NUXT_STRICT_FETCH,
    Technology.OFETCH,
  ],
  [Category.BACKEND]: [
    Technology.NEST,
    Technology.GO,
    Technology.GIN,
    Technology.GORM,
    Technology.PHP,
    Technology.LARAVEL,
    Technology.POSTGRE_SQL,
    Technology.MY_SQL,
    Technology.REDIS,
    Technology.SOCKET_IO,
  ],
  [Category.DEVOPS]: [
    Technology.DOCKER,
    Technology.KUBERNETES,
    Technology.NGINX,
    Technology.GITHUB_ACTIONS,
    Technology.GITLAB_CI,
    Technology.CADDY,
  ],
} satisfies Record<Category, Technology[]>;

type _1 = AssertTrue<SameUnion<(typeof TECHNOLOGY_GROUP)[Category][number], Technology>>;
